# Generated by Django 6.0.7 on 2026-07-30 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Entrada')),
                ('check_out', models.DateField(verbose_name='Salida')),
                ('guests', models.PositiveIntegerField(default=1, verbose_name='Número de huéspedes')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('completed', 'Finalizada')], default='confirmed', max_length=20, verbose_name='Estado')),
                ('internal_notes', models.TextField(blank=True, help_text='Notas internas específicas de esta estancia.', verbose_name='Observaciones de la reserva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Huésped')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('admin_notes', models.TextField(blank=True, help_text='Notas privadas sobre el huésped visibles únicamente para los administradores.', verbose_name='Observaciones internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
